language: java
jdk:
  - oraclejdk7
  - oraclejdk8
before_install:
  - sudo apt-get install -y -qq stunnel
install: make prepare ssl-keys
script: make test-coveralls
cache:
  directories:
    - $HOME/.m2/repository

