language: java

jdk:
  - openjdk12
  - openjdk11
  - openjdk8

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

env:
  global:
    - secure: "dPX83x9q53WLJjNEsOJZTj2yjcusMp3Rg2SeF9xGUgxLa0NAdiWKM/ejSiJO\nzRM+5nmnQGb4SSigqb99N0ndB0S5YhMzbpACD8+SmCfpYRPdUQtE5dW22xpd\nPGPPUwPAGcqISwq5lcFCbPeve8k4g5Co/ZWGMMkoYy8DfjRss6g="
    - secure: "X/+tqgmKqR6wIvSLzDyYAc3Q0NtzFjnQZT7b4yD9MI+/9S1bLFyZJ8mLhymK\nEakyrz8syFAl38ebl2pGox3yaJ9GRfcQXjJ2Qv0Pgb0r+RQTrtU2Fpvb+3Nr\nh5ymtRIkU0XOpOBCq5M9AxV1TESftw3p1IUD9dzPilRqQdXzTGs="
