dist: xenial

language: java

env:
  matrix:
    - REDIS=5.0
    - PROFILE=jmh
    - REDIS=4.0.13
    - REDIS=3.2.13

sudo: false

before_install:
  - if [[ ! -f downloads/stunnel-5.54.tar.gz ]]; then wget -O downloads/stunnel-5.54.tar.gz ftp://ftp.stunnel.org/stunnel/archive/5.x/stunnel-5.54.tar.gz; fi
  - if [[ ! -f ./stunnel-5.54/configure ]]; then tar -xzf downloads/stunnel-5.54.tar.gz; fi
  - if [[ ! -f ./stunnel-5.54/src/stunnel ]]; then cd ./stunnel-5.54; ./configure; make; cd ..; fi
  - export PATH="$PATH:$(pwd)/stunnel-5.54/src"

install: make prepare ssl-keys

script: make test-coverage PROFILE=${PROFILE:-ci}

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$TRAVIS_BUILD_DIR/downloads'
    - '$TRAVIS_BUILD_DIR/stunnel-5.54'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7c2a962829d225c47a31
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
