site_name: Lettuce Reference Guide
repo_url: https://github.com/redis/lettuce
theme:
  name: material
  logo: static/logo-redis.svg
  favicon: static/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: 'Geist'
    code: 'Geist Mono'
  features:
    - content.code.copy
    - navigation.footer
  palette:
    primary: white
    accent: red
extra_css:
  - css/extra.css
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/redisinc
    - icon: fontawesome/brands/discord
      link: https://discord.gg/redis
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/redisinc
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/redisinc

plugins:
  - search
  - macros:
      include_dir: .

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
nav:
  - Overview: overview.md
  - New & Noteworthy: new-features.md
  - Getting Started: getting-started.md
  - Compatibility & Roadmap: compatibility-roadmap.md
  - User Guide:
      - Connecting Redis: user-guide/connecting-redis.md
      - Asynchronous API: user-guide/async-api.md
      - Reactive API: user-guide/reactive-api.md
      - Kotlin API: user-guide/kotlin-api.md
      - Publish/Subscribe: user-guide/pubsub.md
      - Transactions/Multi: user-guide/transactions-multi.md
      - Redis Query Engine: user-guide/redis-search.md
      - Redis JSON: user-guide/redis-json.md
      - Redis Vector Sets: user-guide/vector-sets.md
      - Redis programmability:
          - LUA Scripting: user-guide/lua-scripting.md
          - Redis Functions: user-guide/redis-functions.md
  - High-Availability and Sharding: ha-sharding.md
  - Working with dynamic Redis Command Interfaces: redis-command-interfaces.md
  - Advanced Usage: advanced-usage.md
  - Integration and Extension: integration-extension.md
  - Frequently Asked Questions: faq.md
  - API Reference: https://www.javadoc.io/doc/io.lettuce/lettuce-core/latest/index.html
  - JMH Micro-benchmarks: static/benchmarks/index.html
